//------------------------------------------------------------------------------
//
// File:        lrhtcp.h
// Description: (LightWhale Protocol) definitions of lrhtcp at its fullest
//
//------------------------------------------------------------------------------
//
// File generated on jan 2025 by Rin Baudelet
//------------------------------------------------------------------------------

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
#ifndef _lrhtcp_h_
#define _lrhtcp_h_

// Local
#include "lrhtcp-defs.h"

// C standard lib
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

//
// Macro values defining the protocol
//

#define LP_HEADER_PROTOCOL_VERSION   1  // version of 2025/02
#define LP_PAYLOAD_MAX_LENGTH      255

// --- HEADER FLAGS --- //

#define LP_HEADER_FLAGS_LOWRATE    0x1 // disable high-rate default feature

// --- FREQUENCY PLANS (by zone) --- //

#define LP_FREQUENCY_PLAN_UNDEFINED 0x00

// EUROPEAN PLANS
#define LP_FREQUENCY_PLAN_EU863_70  0x11
#define LP_FREQUENCY_PLAN_EU443     0x12

// AMERICAN PLANS
#define LP_FREQUENCY_PLAN_US902_28  0x21

// --- FREQUENCY PLANS (by country) --- //

// FRANCE
#define LP_FREQUENCY_PLAN_CNTRY_FRANCE_HIGH LP_FREQUENCY_PLAN_EU863_70
#define LP_FREQUENCY_PLAN_CNTRY_FRANCE_LOW  LP_FREQUENCY_PLAN_EU443

// CANADA
#define LP_FREQUENCY_PLAN_CNTRY_CANADA      LP_FREQUENCY_PLAN_US902_28

// --- LP ADDRESS SPECS --- //

#define LP_ADDRESS_TYPE_LPV1        0x0 // use address assigned by the network provider (32 bits)
#define LP_ADDRESS_TYPE_CUSTOM      0x1 // custom address (may have conflicted, 32 bits)
#define LP_ADDRESS_TYPE_RESERVED    0x3 // for future purpose

#define LP_DEVID_PRIVATE      0x0000 //< /4 (0000-1FFF)
#define LP_DEVID_EXPERIMENTAL 0x2000 //< /4 (2000-3FFF)

// --- LORA SPECIFICATIONS --- //

#define LP_LORA_CR4_8    0x08
#define LP_LORA_CR4_7    0x07
#define LP_LORA_CR4_6    0x06
#define LP_LORA_CR4_5    0x05

#define LP_LORA_SF7      0x07
#define LP_LORA_SF8      0x08
#define LP_LORA_SF9      0x09
#define LP_LORA_SF10     0x0A
#define LP_LORA_SF11     0x0B
#define LP_LORA_SF12     0x0C
#define LP_LORA_FSK      0x50

//
// Enumerations values
//

/**
 * Tells which service the packet/payload is sent for.
 * @details code on four bits (0 to 15)
 */
typedef enum lwp_service_type
{
    // Ping device
    k_lwp_service_ping          = 0x0,

    // Synchronize p2p communication
    k_lwp_service_sync_request  = 0x1, //< require channel synch for COM
    k_lwp_service_sync_reply    = 0x2, //< reply channel synch for COM
    k_lwp_service_sync_afa      = 0x3, //< request new sync for adaptative frequency agility

    // Control
    k_lwp_service_comm_transmit = 0x4, //< transmit data
    k_lwp_service_comm_config   = 0x5, //< adjust TCP frame width, LBT delay, etc.
    k_lwp_service_comm_ack      = 0x6, //< acknowlegde packet
    k_lwp_service_comm_nack     = 0x7, //< packet missing, re-send packet

} lwp_service_t;

/**
 *
 */
typedef enum lwp_protocol_type
{
    k_lwp_protocol_p2p = 0x0, // peer to peer communication using LRHTCP
    k_lwp_protocol_net = 0x1, // gateway to internet using LRHTCP (TCP)

    k_lwp_protocol_undefined = 0xf,

} lwp_protocol_t;

//
// Union and other types
//

typedef union lp_address
{
    uint8_t     bytes[4];
    uint32_t    dword;

    struct detail_definition
    {
        /**
         *
         */
        uint8_t  lp_type : 2;
        /**
         *
         */
        uint16_t dev_id  : 14;
        /**
         *
         */
        uint16_t suffix  : 16;
    } __lrhtcp_packet__ detail;
} lp_address_t;

typedef struct lp_ping_result
{
    lp_address_t address;
    uint8_t      lora_sf;
    uint8_t      lora_cr;
} lp_ping_result_t;

typedef uint32_t        lpIPV4;
typedef uint16_t        lpIPV6[8];

//
// Packets
//

/**
 * Define common header for every LRHTCP packet
 */
typedef struct lwp_lp_header
{
    /**
     *
     */
    uint8_t lpVersion : 4;
    /**
     *
     */
    uint8_t lpHeaderLength : 4;

    /**
     *
     */
    lwp_service_t service : 4;

    /**
     *
     */
    uint8_t flags : 4;

    /**
     * Communication identifier generated by the sender. Allow authentication
     * of every payload and N/ACK message from the receiver.
     */
    uint8_t identifier : 8; // 1

    /**
     * Specify current communication total length in bytes.
     * The Maximum total length is 262,143 bytes.
     */
    uint32_t totalLength : 18;

    /**
     * Increment every packet sent.
     * @note Since the offset is defined on 16 bits, it means that only 65536 packets
     * can be sent per communication. Otherwise, communication will be split.
     */
    uint16_t fragmentOffset; // 2

    /**
     * (Required) lightwhale (lora) protocol host's address.
     */
    lp_address_t lpHostAddress; // 4

    /**
     * (p2p, server-side net) lightwhale (lora) protocol destination's address.
     *
     * \note This address is only necessary for a p2p communication or for server-side
     *       net communication.
     */
    lp_address_t lpDestinationAddress; // 4
} __lrhtcp_packet__ lwp_packet_header_t;

#define __lrhtcp_header__ lwp_packet_header_t lpHeader;

// --- //

typedef struct lwp_sync_data
{
    // Bandwidth
    uint16_t bandwidth;

    // Frequency
    uint32_t channel;
} __lrhtcp_packet__ lwp_sync_data_t, lwp_channel_t;

typedef struct lwp_sync_frame_request
{
    // LP Header
    __lrhtcp_header__

    uint8_t sync_data_length;      // count of channels available
    uint8_t sync_spreading_factor; // current spreading factor used to reach the device
    lwp_sync_data_t sync_data[10]; // sort in order of preferences, 10 maximums
} __lrhtcp_packet__ lwp_lp_sync_frame_rqst_t;

typedef struct lwp_sync_frame_reply
{
    // LP Header
    __lrhtcp_header__

    lwp_sync_data_t sync_data;
} __lrhtcp_packet__ lwp_sync_frame_resp_t;

//
// Socket
//

typedef struct lwp_socket LwpSocket, *pLwpSocket;
struct lwp_socket
{
    /**
     * Synchronization channel used for PING and OTAA (over-the-air activation)
     */
    lwp_channel_t syncChannel;

    /**
     * Current communication channel. Define when sync request/reply done
     */
    lwp_channel_t comChannel;

    /**
     * Current COM frequency plan
     */
    uint8_t frequencyPlan;

    /**
     * Delay before any COM operation is considered as timed-out
     * \note value in ms, i.e maximum timeout is 65535 seconds
     */
    uint16_t comTimeout;

    /**
     * Address bind to the socket. Specify with which device communication is performed.
     */
    lp_address_t bindAddress;

    /**
     *
     */
    lwp_protocol_t protocolType;
} __attribute__((__packed__, aligned(4)));

// --- //

#define LP_PAYLOAD_DATA_MAX_LENGTH (LP_PAYLOAD_MAX_LENGTH-sizeof(lwp_packet_header_t))

typedef struct lwp_data_frame
{
    __lrhtcp_header__

    /**
     * Data to send.
     */
    union data_type
    {
        struct tcp_config
        {
            uint32_t lbtDelay;
            uint16_t comWindowWidth;
        } __lrhtcp_packet__ tcpConfig;

        uint8_t raw[LP_PAYLOAD_DATA_MAX_LENGTH];
    } __lrhtcp_packet__ data;

} __lrhtcp_packet__ lwp_data_frame_t;

//
// LRHTCP Packet init
//

/**
 *
 * @param socket
 * @return
 */
uint8_t LpGetFrequencyPlan(pLwpSocket socket);
/**
 *
 * @param socket
 * @param frequencyPlan
 * @return
 */
void LpSetFrequencyPlan(pLwpSocket socket, uint8_t frequencyPlan);

/**
 *
 * @param frequencyPlan
 * @return
 */
LwpSocket* LpCreateSocket(uint8_t frequencyPlan);

//
// LRHTCP COM methods
//

/**
 * Server-Side, listen to the current socket.
 * If the synchronization hasn't been performed yet, sync will be done first.
 * @param socket
 */
bool LpListen(pLwpSocket socket);

/**
 * Server-Side, listen to the current socket as a gateway.
 * @param socket
 * @return
 */
bool LpGateway(pLwpSocket socket);

/**
 *
 * @param socket
 */
void LpAccept(pLwpSocket socket);

/**
 * Client-Side, bind to server (p2p).
 * @param socket
 * @param lpdest
 */
bool LpBind(pLwpSocket socket, lp_address_t lpdest);

/**
 * Client-side, bind to server (net)
 * @param socket
 * @param netaddr the internet protocol address of the actual target.
 * @return
 */
bool LpBind2Net(pLwpSocket socket, lpIPV4 netaddr);
// bool LpBind2Netv6(pLwpSocket socket, lpIPV6 netaddr);

/**
 *
 * @param socket
 * @param data
 * @param length
 * @return
 */
size_t LpSend(pLwpSocket socket, const void* data, size_t length);

/**
 *
 * @param socket
 * @param data
 * @param length
 * @return
 */
size_t LpRecv(pLwpSocket socket, void* data, size_t length);

/**
 *
 * @param socket
 */
void LpClose(pLwpSocket socket);

#endif // _lrhtcp_h_
